FROM paasman/paasman-src

MAINTAINER paasman

RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update

#ADD ../../

CMD ["/bin/echo", "hello this is paasman"]
